theme = "everforest_light"
# Themes i like
#
# ayu_mirage *
# snazzy
# bogster
# amberwood
# ayu-evolve (darker contrast)
# ayu-dark
# doom_acario_dark (colder)
#
# Light
# adwaita-light (good for outdoors, very white)
# catpuccin_latte (more blueish)
# everforest_light (feels like summer, a bit yellower)
# kaolin-light (feels more paper-like)
# seoul-light-soft (even more grayish and soft, paper-like)

[editor]
mouse=false
gutters=["diagnostics", "diff", "spacer"]
end-of-line-diagnostics="hint"

[editor.inline-diagnostics]
cursor-line="error"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-inlay-hints = false

[editor.auto-save]
# NOTE: doesn't work with autosafe + autoformat
after-delay.enable = true
after-delay.timeout = 1000

[editor.indent-guides]
render = true
character = "0"

[keys.normal]
# NOTE: some commands have ":w" to fight issue with autosave+autoformat
esc = ["collapse_selection",":w", "keep_primary_selection"]
";" = "command_mode"
C-g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
# NOTE: this copies into clipboard
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"
c = ["yank_to_clipboard", "change_selection_noyank"]
d = ["yank_to_clipboard", "delete_selection_noyank"]

[keys.normal.space]
w=":write"
q=":quit"


[editor.cursor-shape]
insert="bar"
select="underline"

[keys.select]
"esc" = ["collapse_selection", "normal_mode", ":w"]

[keys.insert]
"esc" = ["normal_mode", ":w"]


