theme = "everforest_light"
# Themes i like
#
# ayu_mirage *
# snazzy
# bogster
# amberwood
# ayu-evolve (darker contrast)
# ayu-dark
# doom_acario_dark (colder)
#
# Light
# adwaita-light (good for outdoors, very white)
# catpuccin_latte (more blueish)
# everforest_light (feels like summer, a bit yellower)
# kaolin-light (feels more paper-like)
# seoul-light-soft (even more grayish and soft, paper-like)

[editor]
mouse=false
# bufferline="multiple"
gutters=["diagnostics", "diff", "spacer"]
end-of-line-diagnostics="hint"

[editor.inline-diagnostics]
cursor-line="error"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-inlay-hints = false

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 1000 

# NOTE: if autosafe wn't work properly, i can add ":w" to esc commands, to save on escape
 
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
";" = "command_mode"
C-g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"
c = ["yank_to_clipboard", "change_selection_noyank"]
d = ["yank_to_clipboard", "delete_selection_noyank"]

[keys.normal.space]
w=":write"
q=":quit"


[editor.cursor-shape]
insert="bar"
select="underline"

