theme = "dark_high_contrast"

[editor]
mouse=false
# bufferline="multiple"
gutters=["diagnostics", "diff", "spacer"]
end-of-line-diagnostics="hint"

[editor.inline-diagnostics]
cursor-line="error"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-inlay-hints = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
";" = "command_mode"
C-g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]

[keys.normal.space]
w=":write"
q=":quit"


[editor.cursor-shape]
insert="bar"
select="underline"
